# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud_replay.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'cloud_replay.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import livekit_models_pb2 as livekit__models__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63loud_replay.proto\x12\x06replay\x1a\x1bgoogle/protobuf/empty.proto\x1a\x14livekit_models.proto\"U\n\x12ListReplaysRequest\x12\x11\n\troom_name\x18\x01 \x01(\t\x12,\n\npage_token\x18\x02 \x01(\x0b\x32\x18.livekit.TokenPagination\"m\n\x13ListReplaysResponse\x12#\n\x07replays\x18\x01 \x03(\x0b\x32\x12.replay.ReplayInfo\x12\x31\n\x0fnext_page_token\x18\x02 \x01(\x0b\x32\x18.livekit.TokenPagination\"X\n\nReplayInfo\x12\x11\n\treplay_id\x18\x01 \x01(\t\x12\x11\n\troom_name\x18\x02 \x01(\t\x12\x12\n\nstart_time\x18\x03 \x01(\x03\x12\x10\n\x08\x64uration\x18\x04 \x01(\x03\"(\n\x13\x44\x65leteReplayRequest\x12\x11\n\treplay_id\x18\x01 \x01(\t\"P\n\x0fPlaybackRequest\x12\x11\n\treplay_id\x18\x01 \x01(\t\x12\x15\n\rplayback_room\x18\x02 \x01(\t\x12\x13\n\x0bseek_offset\x18\x03 \x01(\x03\"\'\n\x10PlaybackResponse\x12\x13\n\x0bplayback_id\x18\x01 \x01(\t\"7\n\x0bSeekRequest\x12\x13\n\x0bplayback_id\x18\x01 \x01(\t\x12\x13\n\x0bseek_offset\x18\x02 \x01(\x03\"+\n\x14\x43losePlaybackRequest\x12\x13\n\x0bplayback_id\x18\x01 \x01(\t2\xc8\x02\n\x06Replay\x12\x46\n\x0bListReplays\x12\x1a.replay.ListReplaysRequest\x1a\x1b.replay.ListReplaysResponse\x12\x43\n\x0c\x44\x65leteReplay\x12\x1b.replay.DeleteReplayRequest\x1a\x16.google.protobuf.Empty\x12=\n\x08Playback\x12\x17.replay.PlaybackRequest\x1a\x18.replay.PlaybackResponse\x12\x33\n\x04Seek\x12\x13.replay.SeekRequest\x1a\x16.google.protobuf.Empty\x12=\n\x05\x43lose\x12\x1c.replay.ClosePlaybackRequest\x1a\x16.google.protobuf.EmptyBEZ\"github.com/livekit/protocol/replay\xaa\x02\rLiveKit.Proto\xea\x02\x0eLiveKit::Protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud_replay_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\"github.com/livekit/protocol/replay\252\002\rLiveKit.Proto\352\002\016LiveKit::Proto'
  _globals['_LISTREPLAYSREQUEST']._serialized_start=81
  _globals['_LISTREPLAYSREQUEST']._serialized_end=166
  _globals['_LISTREPLAYSRESPONSE']._serialized_start=168
  _globals['_LISTREPLAYSRESPONSE']._serialized_end=277
  _globals['_REPLAYINFO']._serialized_start=279
  _globals['_REPLAYINFO']._serialized_end=367
  _globals['_DELETEREPLAYREQUEST']._serialized_start=369
  _globals['_DELETEREPLAYREQUEST']._serialized_end=409
  _globals['_PLAYBACKREQUEST']._serialized_start=411
  _globals['_PLAYBACKREQUEST']._serialized_end=491
  _globals['_PLAYBACKRESPONSE']._serialized_start=493
  _globals['_PLAYBACKRESPONSE']._serialized_end=532
  _globals['_SEEKREQUEST']._serialized_start=534
  _globals['_SEEKREQUEST']._serialized_end=589
  _globals['_CLOSEPLAYBACKREQUEST']._serialized_start=591
  _globals['_CLOSEPLAYBACKREQUEST']._serialized_end=634
  _globals['_REPLAY']._serialized_start=637
  _globals['_REPLAY']._serialized_end=965
# @@protoc_insertion_point(module_scope)
