# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_token_source.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'livekit_token_source.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import livekit_room_pb2 as livekit__room__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1alivekit_token_source.proto\x12\x07livekit\x1a\x12livekit_room.proto\"\xc2\x03\n\x12TokenSourceRequest\x12\x16\n\troom_name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1d\n\x10participant_name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12!\n\x14participant_identity\x18\x03 \x01(\tH\x02\x88\x01\x01\x12!\n\x14participant_metadata\x18\x04 \x01(\tH\x03\x88\x01\x01\x12V\n\x16participant_attributes\x18\x05 \x03(\x0b\x32\x36.livekit.TokenSourceRequest.ParticipantAttributesEntry\x12\x34\n\x0broom_config\x18\x06 \x01(\x0b\x32\x1a.livekit.RoomConfigurationH\x04\x88\x01\x01\x1a<\n\x1aParticipantAttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x0c\n\n_room_nameB\x13\n\x11_participant_nameB\x17\n\x15_participant_identityB\x17\n\x15_participant_metadataB\x0e\n\x0c_room_config\"D\n\x13TokenSourceResponse\x12\x12\n\nserver_url\x18\x01 \x01(\t\x12\x19\n\x11participant_token\x18\x02 \x01(\tBFZ#github.com/livekit/protocol/livekit\xaa\x02\rLiveKit.Proto\xea\x02\x0eLiveKit::Protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'livekit_token_source_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#github.com/livekit/protocol/livekit\252\002\rLiveKit.Proto\352\002\016LiveKit::Proto'
  _globals['_TOKENSOURCEREQUEST_PARTICIPANTATTRIBUTESENTRY']._loaded_options = None
  _globals['_TOKENSOURCEREQUEST_PARTICIPANTATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_TOKENSOURCEREQUEST']._serialized_start=60
  _globals['_TOKENSOURCEREQUEST']._serialized_end=510
  _globals['_TOKENSOURCEREQUEST_PARTICIPANTATTRIBUTESENTRY']._serialized_start=349
  _globals['_TOKENSOURCEREQUEST_PARTICIPANTATTRIBUTESENTRY']._serialized_end=409
  _globals['_TOKENSOURCERESPONSE']._serialized_start=512
  _globals['_TOKENSOURCERESPONSE']._serialized_end=580
# @@protoc_insertion_point(module_scope)
